sudo: required
services:
  - docker

before_install:
  - docker build -t ashil/react-test -f ./client/Dockerfile.dev ./client

#test runner section
script:
  - docker run ashil/react-test npm test -- --coverage

after_success:
  - docker build -t ashil/multi-docker-client ./client
  - docker build -t ashil/multi-docker-server ./server
  - docker build -t ashil/multi-docker-worker ./worker
  - docker build -t ashil/multi-docker-nginx ./nginx
  # login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images to docker hub
  - docker push ashil/multi-docker-client
  - docker push ashil/multi-docker-server
  - docker push ashil/multi-docker-worker
  - docker push ashil/multi-docker-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-025474164248
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
